#!/bin/sh
# postinst script for vpn-admin-portal
#
# see: dh_installdeb(1)

set -e

if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi

case "$1" in
    configure)
        chown www-data:www-data /var/lib/vpn-admin-portal
        chmod 700 /var/lib/vpn-admin-portal

	if [ ! -d /etc/vpn-admin-portal/ ]; then
		install -d -m 750 /etc/vpn-admin-portal
	fi

	# Make sure ownership is allright
	chown -R root:www-data /etc/vpn-admin-portal
	chmod 750 /etc/vpn-admin-portal

	# Check if we are upgrading, the upgrade
	# file is written by preinst upgrade
	if [ -f /etc/vpn-admin-portal/.upgrade ]; then
		echo "Upgrade, not touching configuration"
		rm  /etc/vpn-admin-portal/.upgrade
	else
		# This is a new installation. Try to create default config
		if [ ! -d /etc/vpn-admin-portal/default ]; then
			echo "New installation, creating default configuration"
			install -d -m 755 /etc/vpn-admin-portal/default
			if [ -f /usr/share/doc/vpn-admin-portal/config.php.example ]; then
				install -m 644 /usr/share/doc/vpn-admin-portal/config.php.example \
				  /etc/vpn-admin-portal/default/config.php
			elif [ -f /usr/share/doc/vpn-admin-portal/config.php.example.gz ]; then
				zcat /usr/share/doc/vpn-admin-portal/config.php.example.gz \
				  >/etc/vpn-admin-portal/default/config.php
			fi
		else
			echo "New installation, but existing default configuration found. Not updating"
		fi
	fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
