#!/bin/sh
# preinst script for vpn-admin-portal
#
# see: dh_installdeb(1)

set -e

if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi

case "$1" in
    upgrade)
	# Mark upgrade    
        touch /etc/vpn-admin-portal/.upgrade
    ;;
    
esac


exit 0
