#!/bin/sh
# postinst script for vpn-user-portal
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        chown -R www-data:www-data /var/lib/vpn-user-portal
        chmod -R 700 /var/lib/vpn-user-portal


	if [ ! -d /etc/vpn-user-portal/ ]; then
		install -d -m 750 /etc/vpn-user-portal
	fi

	# Make sure ownership is allright
	chown -R root:www-data /etc/vpn-user-portal
	chmod 750 /etc/vpn-user-portal

	# Check if we are upgrading, the upgrade
	# file is written by preinst upgrade
	if [ -f /etc/vpn-user-portal/.upgrade ]; then
		echo "Upgrade, not touching configuration"
		rm  /etc/vpn-user-portal/.upgrade
	else
        # generate OAuth key if it does not exist
        if [ ! -f /etc/vpn-user-portal/oauth.key ]; then
            /usr/bin/vpn-user-portal-generate-oauth-key
        fi

		# This is a new installation. Try to create default config
		if [ ! -f /etc/vpn-user-portal/config.php ]; then
			if [ -f /usr/share/doc/vpn-user-portal/config.php.example ]; then
				install -m 644 /usr/share/doc/vpn-user-portal/config.php.example \
				       /etc/vpn-user-portal/config.php
			elif [ -f /usr/share/doc/vpn-user-portal/config.php.example.gz ]; then
				zcat /usr/share/doc/vpn-user-portal/config.php.example.gz \
				       >/etc/vpn-user-portal/config.php
			fi
		else
			echo "New installation, but existing default configuration found. Not updating"
		fi
	fi

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
