#!/bin/sh
# postinst script for vpn-user-portal
#
# see: dh_installdeb(1)

set -e

if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi

case "$1" in
    configure)
        chown -R www-data:www-data /var/lib/vpn-user-portal
        chmod -R 700 /var/lib/vpn-user-portal
        chmod 755 usr/share/vpn-user-portal/bin/*
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
