#!/bin/sh
# postrm script for vpn-user-portal
#
# see: dh_installdeb(1)

set -e

case "$1" in
    failed-upgrade|abort-install|abort-upgrade|disappear|remove)
    ;;

    purge)
        rm -rf /var/lib/vpn-user-portal
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
