#!/bin/sh
# postinst script for php-saml-ds
#
# see: dh_installdeb(1)

set -e

if [ -f /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
fi

case "$1" in
    configure)
	chown www-data:www-data /var/lib/php-saml-ds
	chmod 700 /var/lib/php-saml-ds
	chmod 755 /usr/share/php-saml-ds/bin/generate.php
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

