#!/bin/sh
# postrm script for php-saml-ds
#
# see: dh_installdeb(1)

set -e

if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi

case "$1" in
    failed-upgrade|abort-install|abort-upgrade|disappear|remove|upgrade)
    ;;

    purge)
        rm -rf /var/lib/php-saml-ds
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


