#!/bin/sh

set -e

case "$1" in
    configure)

	    if [ ! -d /etc/vpn-user-portal ]
        then
		    install -d -m 750 /etc/vpn-user-portal
    	    chown -R root:www-data /etc/vpn-user-portal
	    fi

	    if [ ! -f /etc/vpn-user-portal/LC.php ]
        then
		    if [ -f /usr/share/doc/vpn-portal-artwork-lc/LC.php.example ]
            then
			    install -m 644 /usr/share/doc/vpn-portal-artwork-lc/LC.php.example /etc/vpn-user-portal/LC.php
		    elif [ -f /usr/share/doc/vpn-portal-artwork-lc/LC.php.example.gz ]
            then
			    zcat /usr/share/doc/vpn-portal-artwork-lc/LC.php.example.gz >/etc/vpn-user-portal/LC.php
		    fi
	    fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
