#!/bin/sh

set -e

case "$1" in
    configure)

	    if [ ! -d /etc/vpn-user-portal ]
        then
		    install -d -m 750 /etc/vpn-user-portal
    	    chown -R root:www-data /etc/vpn-user-portal
	    fi	
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
