#!/bin/sh
# postrm script for vpn-server-api
#
# see: dh_installdeb(1)

set -e

case "$1" in
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|remove)
    ;;
    purge)
        rm -rf /var/lib/vpn-server-api
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
