#!/bin/sh
# postinst script for vpn-server-api
#
# see: dh_installdeb(1)

set -e

if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi

case "$1" in
    configure)
        chown www-data:www-data /var/lib/vpn-server-api
        chmod 700 /var/lib/vpn-server-api
        chmod 755 /usr/share/vpn-server-api/bin/*
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
