#!/bin/sh
# preinst script for vpn-server-api
#
# see: dh_installdeb(1)

set -e

if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi

case "$1" in
    upgrade)
	# Mark upgrade
        touch /etc/vpn-server-api/.upgrade
    ;;
esac

#DEBHELPER#
